const API="https://correio-content-hub.onrender.com/api/v1/sites/by-domain/articles?domain=revistadegastronomia.com.br";
const fallback=[
{id:101,title:"O ingrediente de R$ 3 que transforma qualquer molho de tomate",description:"Um detalhe simples muda aroma, textura e sabor.",category:"receitas",author:"Redação",image_url:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=85",content:"Cozinhar bem não depende de ingredientes caros. O segredo está no tempo, na temperatura e na maneira de combinar sabores.\nComece com uma boa base aromática e deixe o tomate cozinhar lentamente. Finalize provando e corrigindo a acidez aos poucos."},
{id:102,title:"A pequena casa de massas que virou a reserva mais disputada da cidade",description:"Massa fresca, salão intimista e uma fila que cresce a cada semana.",category:"restaurantes",author:"Redação",image_url:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=85",content:"O restaurante começou pequeno, com poucas mesas e um cardápio escrito à mão. A atenção aos ingredientes rapidamente conquistou o bairro.\nHoje, a cozinha mantém o ritmo artesanal e transforma receitas tradicionais em pratos cheios de personalidade."},
{id:103,title:"7 mercados gastronômicos que valem uma viagem só para comer",description:"Sabores, aromas e tradições reunidos em lugares inesquecíveis.",category:"viagens",author:"Redação",image_url:"https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=1200&q=85",content:"Mercados contam a história de uma cidade por meio de seus ingredientes. Caminhar entre bancas é descobrir hábitos, sotaques e receitas.\nSelecionamos destinos onde a comida é a melhor porta de entrada para a cultura local."},
{id:104,title:"O café gelado mais cremoso do verão leva três ingredientes",description:"Uma receita rápida para tardes quentes.",category:"bebidas",author:"Redação",image_url:"https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1200&q=85",content:"Prepare um café forte e espere esfriar completamente. O gelo deve entrar apenas no final para não diluir a bebida.\nBata os ingredientes até obter uma textura leve e sirva imediatamente."},
{id:105,title:"Por que todo mundo está colocando mel na pizza?",description:"Provamos a combinação que divide opiniões.",category:"tendencias",author:"Redação",image_url:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=85",content:"O contraste entre doce, salgado e picante explica o sucesso da combinação. Em pequenas quantidades, o mel realça queijos intensos.\nA tendência nasceu em pizzarias artesanais e chegou rapidamente às cozinhas domésticas."},
{id:106,title:"O jantar leve que não abre mão do sabor",description:"Pronto em 20 minutos com ingredientes simples.",category:"receitas",author:"Redação",image_url:"https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=85",content:"Legumes frescos, uma boa fonte de proteína e um molho equilibrado formam uma refeição completa.\nA receita pode variar conforme a estação e funciona tanto quente quanto fria."}
];
const icon=(name)=>({menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/></svg>',arrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 15 6-6 6 6"/></svg>'}[name]||"");
const navLinks=()=>'<a href="editoria.html?categoria=receitas">Receitas</a><a href="editoria.html?categoria=restaurantes">Restaurantes</a><a href="editoria.html?categoria=tendencias">Tendências</a><a href="editoria.html?categoria=viagens">Viagens</a><a href="editoria.html?categoria=bebidas">Bebidas</a><a href="editoria.html?categoria=curiosidades">Curiosidades</a>';
const header=()=>`<div class="reading-progress" id="reading-progress"></div><div class="topline"><span>EDIÇÃO DIGITAL · ATUALIZAÇÃO CONTÍNUA</span><span>O prazer de comer bem, todos os dias.</span></div><header class="portal-header"><div class="header-main"><button class="icon-button menu-toggle" aria-label="Abrir menu" aria-expanded="false">${icon("menu")}</button><a class="brand" href="index.html"><span>REVISTA DE</span><strong>GASTRONOMIA</strong><em>desde 2026</em></a><a class="icon-button search-link" href="busca.html" aria-label="Pesquisar">${icon("search")}</a></div><nav class="desktop-nav">${navLinks()}<a href="busca.html">Buscar</a></nav><div class="mobile-drawer" aria-hidden="true"><div class="drawer-head"><b>Menu</b><button class="icon-button menu-close" aria-label="Fechar menu">${icon("close")}</button></div><nav>${navLinks()}<a href="busca.html">Buscar</a><a href="sobre.html">Sobre</a><a href="anuncie.html">Anuncie</a></nav></div><div class="drawer-backdrop"></div></header>`;
const footer=()=>`<footer><a class="brand footer-brand" href="index.html"><span>REVISTA DE</span><strong>GASTRONOMIA</strong></a><p>Comer é cultura. Cozinhar é memória.</p><div><a href="sobre.html">Sobre</a><a href="contato.html">Contato</a><a href="privacidade.html">Privacidade</a><a href="anuncie.html">Anuncie</a></div><small>© 2026 Revista de Gastronomia.</small></footer>`;
const ad=(type="leaderboard")=>`<aside class="ad-slot ${type}"><span>PUBLICIDADE</span><div>ESPAÇO PUBLICITÁRIO</div></aside>`;
const card=a=>`<a class="listing-card" href="materia.html?id=${a.id}">${a.image_url?`<img src="${a.image_url}" alt="">`:""}<div><span>${a.category||"Gastronomia"}</span><h2>${a.title}</h2><p>${a.description||""}</p></div></a>`;
async function articles(){try{const r=await fetch(`${API}&_=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;const data=await r.json();return data.length?data:fallback}catch{return fallback}}
async function render(){const app=document.querySelector("#portal-app"),page=document.body.dataset.page,data=await articles(),p=new URLSearchParams(location.search);let body="";
if(page==="materia"){const a=data.find(x=>x.id===Number(p.get("id")))||data[0];body=`${ad()}<main class="article-layout"><article class="article-page"><nav class="breadcrumb"><a href="index.html">Início</a> / <a href="editoria.html?categoria=${a.category}">${a.category}</a></nav><span class="eyebrow dark">${a.category}</span><h1>${a.title}</h1><p class="article-deck">${a.description||""}</p><div class="byline">Por ${a.author||"Redação"} · Hoje</div>${a.image_url?`<img class="article-cover" src="${a.image_url}" alt="">`:""}<div class="article-body">${(a.content||a.description||"").split(/\n+/).map(x=>`<p>${x}</p>`).join("")}</div>${ad("in-article")}<div class="share-row"><b>Compartilhe</b><button data-share="whatsapp">WhatsApp</button><button data-share="facebook">Facebook</button><button data-share="copy">Copiar link</button></div></article><aside class="article-rail">${ad("rectangle")}<h2>Mais lidas</h2>${data.slice(0,5).map((x,i)=>`<a class="rail-item" href="materia.html?id=${x.id}"><span>0${i+1}</span>${x.title}</a>`).join("")}</aside></main>`;}
else if(page==="editoria"){const cat=p.get("categoria")||"novidades",shown=data.filter(x=>x.category===cat);body=`${ad()}<main class="content-page"><div class="section-head"><div><span>EDITORIA</span><h1>${cat.replaceAll("-"," ")}</h1></div></div><div class="listing-grid">${(shown.length?shown:data).map(card).join("")}</div>${ad()}</main>`;}
else if(page==="busca"){body=`<main class="content-page"><div class="section-head"><div><span>ENCONTRE UMA HISTÓRIA</span><h1>Busca</h1></div></div><input class="portal-search" id="search" placeholder="Busque receitas, restaurantes e histórias"><div class="listing-grid" id="results">${data.map(card).join("")}</div></main>`;setTimeout(()=>document.querySelector("#search").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelector("#results").innerHTML=data.filter(x=>(x.title+" "+x.description).toLowerCase().includes(q)).map(card).join("")}),0);}
else{const copy={sobre:["Sobre a Revista","A Revista de Gastronomia nasceu para contar histórias sobre comida, cultura, pessoas e lugares. Nossa curadoria reúne receitas, tendências, restaurantes e viagens para quem acredita que comer também é uma forma de conhecer o mundo."],contato:["Fale com a gente","Sugestões de pauta, correções e histórias gastronômicas são bem-vindas. Escreva para contato@revistadegastronomia.com.br."],privacidade:["Política de Privacidade","Respeitamos a privacidade dos leitores. Dados fornecidos em formulários são utilizados somente para prestar o serviço solicitado. Cookies podem ser usados para métricas, personalização e publicidade."],anuncie:["Anuncie conosco","Conecte sua marca a leitores interessados em gastronomia, viagens, bebidas e experiências. Oferecemos formatos de destaque na capa, editorias, matérias e projetos especiais."]}[page];body=`<main class="content-page institutional"><span class="eyebrow dark">REVISTA DE GASTRONOMIA</span><h1>${copy[0]}</h1><p>${copy[1]}</p>${page==="anuncie"?`<div class="ad-products"><div><b>Super banner</b><span>Topo da capa e editorias</span></div><div><b>Retângulo</b><span>Lateral das matérias</span></div><div><b>In-article</b><span>Integrado ao conteúdo</span></div></div><a class="contact-button" href="mailto:comercial@revistadegastronomia.com.br">FALAR COM O COMERCIAL</a>`:""}</main>`;}
app.innerHTML=header()+body+footer();initUI();}
function initUI(){
 const drawer=document.querySelector(".mobile-drawer"),backdrop=document.querySelector(".drawer-backdrop"),toggle=document.querySelector(".menu-toggle");
 const open=()=>{drawer.classList.add("open");backdrop.classList.add("open");drawer.setAttribute("aria-hidden","false");toggle.setAttribute("aria-expanded","true");document.body.classList.add("menu-open")};
 const close=()=>{drawer.classList.remove("open");backdrop.classList.remove("open");drawer.setAttribute("aria-hidden","true");toggle.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open")};
 toggle?.addEventListener("click",open);document.querySelector(".menu-close")?.addEventListener("click",close);backdrop?.addEventListener("click",close);document.addEventListener("keydown",e=>e.key==="Escape"&&close());
 const top=document.createElement("button");top.className="back-to-top";top.setAttribute("aria-label","Voltar ao topo");top.innerHTML=icon("arrow");top.onclick=()=>scrollTo({top:0,behavior:"smooth"});document.body.append(top);
 addEventListener("scroll",()=>{top.classList.toggle("visible",scrollY>500);const max=document.documentElement.scrollHeight-innerHeight;const bar=document.querySelector("#reading-progress");if(bar)bar.style.width=(max?scrollY/max*100:0)+"%"},{passive:true});
 document.querySelectorAll("[data-share]").forEach(button=>button.addEventListener("click",async()=>{const type=button.dataset.share,url=encodeURIComponent(location.href),title=encodeURIComponent(document.title);if(type==="whatsapp")open("https://wa.me/?text="+title+"%20"+url,"_blank");if(type==="facebook")open("https://www.facebook.com/sharer/sharer.php?u="+url,"_blank");if(type==="copy"){await navigator.clipboard.writeText(location.href);button.textContent="Link copiado ✓";}}));
 document.querySelectorAll("img").forEach(img=>{img.loading="lazy";img.decoding="async"});
}
render();