const stories = [
  { tag: "Receitas", title: "O ingrediente de R$ 3 que deixa qualquer molho de tomate com gosto de restaurante", image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85" },
  { tag: "Segredos da cozinha", title: "Você provavelmente sempre cortou a cebola do jeito errado — chefs explicam", image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=900&q=85" },
  { tag: "Restaurantes", title: "A pequena casa de massas que virou a reserva mais disputada da cidade", image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=85" },
  { tag: "Viagem", title: "7 mercados gastronômicos que valem uma viagem só para comer", image: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=900&q=85" },
  { tag: "Bebidas", title: "O café gelado mais cremoso do verão leva apenas três ingredientes", image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=85" },
  { tag: "Curiosidades", title: "Por que todo mundo está colocando mel na pizza? Nós provamos", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85" },
];
const mostRead = ["A regra dos 10 minutos que transforma o arroz de ontem", "O truque do copo d’água para saber se o ovo ainda está bom", "Esta é a melhor manteiga de supermercado, segundo especialistas", "Air fryer: os cinco alimentos que você nunca deveria colocar nela", "O prato brasileiro eleito um dos melhores do mundo"];
function Arrow(){return <span aria-hidden="true">↗</span>}
export default function Home(){return <main>
  <div className="topline"><span>EDIÇÃO DIGITAL · 25 DE AGOSTO DE 2026</span><span>O prazer de comer bem, todos os dias.</span></div>
  <header><div className="header-main"><details className="mobile-menu"><summary aria-label="Abrir menu"><i></i><i></i><i></i></summary><nav><a href="#receitas">Receitas</a><a href="#restaurantes">Restaurantes</a><a href="#tendencias">Tendências</a><a href="#viagens">Viagens</a></nav></details><a className="brand" href="#" aria-label="Revista de Gastronomia"><span>REVISTA DE</span><strong>GASTRONOMIA</strong><em>desde 2026</em></a><button className="search" aria-label="Pesquisar">⌕</button></div><nav className="desktop-nav" aria-label="Navegação principal"><a href="#receitas">Receitas</a><a href="#restaurantes">Restaurantes</a><a href="#tendencias">Tendências</a><a href="#viagens">Viagens</a><a href="#bebidas">Bebidas</a><a href="#curiosidades">Curiosidades</a><a href="#mais-lidas">Mais lidas</a></nav></header>
  <section className="breaking"><b>AGORA</b><div><span>O melhor restaurante do Brasil acaba de ser revelado</span><span>Receita de pão de queijo com 4 ingredientes viraliza</span><span>Chef ensina o ponto perfeito do macarrão</span></div></section>
  <div className="page-shell">
    <section className="hero-grid"><a className="hero" href="#materia"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=90" alt="Mesa repleta de pratos coloridos"/><div className="hero-overlay"><span className="eyebrow">COMIDA DE VERDADE</span><h1>Os 10 pratos que todo brasileiro precisa provar ao menos uma vez</h1><p>Do Norte ao Sul, sabores que contam a nossa história — e onde encontrar cada um deles.</p><b>VER A LISTA <Arrow/></b></div></a><aside className="side-lead"><span className="section-kicker">ESCOLHA DO EDITOR</span><a href="#materia"><img src="https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=85" alt="Prato colorido com legumes frescos"/><span className="eyebrow dark">SAÚDE & SABOR</span><h2>O jantar leve que está conquistando quem não abre mão de comer bem</h2><p>Pronto em 20 minutos e com ingredientes que você já tem em casa.</p></a></aside></section>
    <section className="fresh" id="tendencias"><div className="section-head"><div><span>O QUE ESTÁ FRESCO</span><h2>Novidades para devorar</h2></div><a href="#todas">VER TODAS <Arrow/></a></div><div className="story-grid">{stories.map((story,index)=><a className="story" href="#materia" key={story.title}><div className="story-image"><img src={story.image} alt=""/><span>{story.tag}</span></div><h3>{story.title}</h3><p>Leitura de {index%2===0?"4":"6"} min <Arrow/></p></a>)}</div></section>
    <section className="popular" id="mais-lidas"><div className="popular-intro"><span>TODO MUNDO ESTÁ LENDO</span><h2>As mais<br/><i>apetitosas</i></h2><p>As histórias que despertaram a curiosidade — e a fome — dos nossos leitores nesta semana.</p></div><ol>{mostRead.map((item,index)=><li key={item}><span>0{index+1}</span><a href="#materia">{item}</a><Arrow/></li>)}</ol></section>
    <section className="newsletter"><div><span>UMA CARTA PARA QUEM AMA COMER</span><h2>Receba a nossa seleção mais gostosa.</h2><p>Toda quinta-feira, receitas, lugares e histórias escolhidas a dedo. Sem spam. Só coisa boa.</p></div><form><label className="sr-only" htmlFor="email">Seu melhor e-mail</label><input id="email" type="email" placeholder="Seu melhor e-mail" required/><button type="submit">QUERO RECEBER <Arrow/></button></form></section>
  </div>
  <footer><a className="brand footer-brand" href="#"><span>REVISTA DE</span><strong>GASTRONOMIA</strong></a><p>Comer é cultura. Cozinhar é memória.</p><div><a href="#sobre">Sobre</a><a href="#contato">Contato</a><a href="#privacidade">Privacidade</a><a href="#anuncie">Anuncie</a></div><small>© 2026 Revista de Gastronomia. Todos os direitos reservados.</small></footer>
</main>}
